version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
